pep_version: "2.1.0"

project:
  name: "20251111_cuttag_test"
  sample_table: "../samplesheet_test.csv"
  raw_data: "/storage/zhangkaiLab/hanlitian/macrophage/data/CUTTAG"

paths:
  data_dir: "/storage/zhangkaiLab/resource/Collaborators/Hanjie_Li/CUT-seq"
  process_dir: "/storage/zhangkaiLab/hanlitian/macrophage/process"
  database_dir: "/storage/zhangkaiLab/hanlitian/database/algin_ref/atac_pipeline"
  shared_genome_dir: "/storage/zhangkaiLab/shared/genomes/GRCh38"

sample_modifiers:
  append:
    R1: "{raw_data|data/raw}/{fastq_id}_R1.fastq.gz"
    R2: "{raw_data|data/raw}/{fastq_id}_R2.fastq.gz"
    run_label: "{sample}.{run}"

